/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class App {

    public static void main(String[] args) {
       Disciplina poo = new Disciplina("POO", new
               DiasDaSemana[]{DiasDaSemana.TER, DiasDaSemana.SEX});

        System.out.println(poo);
//        DiasDaSemana d = DiasDaSemana.DOM;
//        d.getCodigo();

    }
}
