/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {
    private Agenda a = new Agenda();

    public static void main(String[] args) {

        
    }
}
