/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {


    public static void main(String[] args) {

        Horario h = new Horario();
        System.out.println(h.toString());
        h.setHora(1);
        System.out.println(h.toString());
        h.setMinuto(1);
        System.out.println(h.toString());
        h.setSegundo(56);
        System.out.println(h.toString());
    }
}
