/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.GregorianCalendar;

public class App {


    public static void main(String[] args) {
        Data d = new Data(24,12,2024);
        Data a = new Data(29,05,2019);
        System.out.println(d);
        System.out.println(d.escreveExtenso());
        System.out.println("a diferença entre datas em dias: " + d.diferenca(a));
    }
}
