/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {


    public static void main(String[] args) {
        Retangulo r = new Retangulo(35,65,"add");
        System.out.println(r.getAltura());
        System.out.println(r.getLargura());
        System.out.println(r.getCodificacao());
    }
}
