/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;
import java.util.Scanner;
public class App {

    public static void main(String[] args) {

        //Scanner linha = new Scanner(System.in);
        //int linhas = 1;

        //while(linha.hasNext()){
            //String aux = linha.nextLine();

            //System.out.println(linhas + "- " + aux.toUpperCase());
            //linhas++;
        if (args.length > 0) {
            System.out.println("Olá " + args[0]);
        }
        }
    }

