/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Ponto a = new Ponto(1.0,2.0);
        Ponto b = new Ponto(3.0,4.0);


        System.out.println("Ponto 1: " + a);
        System.out.println("Ponto 2: " + b);

        System.out.println("distância: " + a.distancia(b));




    }
}
