/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import ads.poo.produtos.Celular;
import ads.poo.produtos.Dimensao;
import ads.poo.produtos.SemFio;
import ads.poo.produtos.Telefone;

public class App {


    public static void main(String[] args) {
//        Telefone t = new Telefone(1,"45", "abc",12, new Dimensao(15,7, 6));
//        Telefone sf = new SemFio(2, "25", "def", 12, new Dimensao(10,5, 2),2.4f, 15,12);
//        System.out.println(t.imprimirDados());
//        System.out.println(sf.imprimirDados());
//        int f = (int) 2.5;
//        System.out.println(f);
//        SemFio c = (SemFio) sf;



//        c.setSistemaOp("Android");
//
//        ((Celular) t).setSistemaOp("Android");
//
//        d = (Celular) t;

        Telefone[] t = new Telefone[4];


        t[0] = new Celular(1,"45", "abc",12, new Dimensao(15,7, 6), "IOS");

        t[1] = new Celular(1,"45", "abc",12, new Dimensao(15,7, 6), "IOS");

        t[2] = new Celular(1,"45", "abc",12, new Dimensao(15,7, 6), "IOS");

        t[3] = new SemFio(2, "25", "def", 12, new Dimensao(10,5, 2),2.4f, 15,12);


        for (Telefone tel : t){
            if(tel instanceof  Celular){
                System.out.println(((Celular) tel).getSistemaOp());
            }
        }


    }
}
