/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.beans.PersistenceDelegate;

public class App {


    public static void main(String[] args) {
        Personagem aldeao = new Aldeao(25,1,0.8);
        Personagem cavaleiro = new Cavaleiro(35, 2, 1);
        Personagem Arqueiro = new Arqueiro(50, 3, 2);

        System.out.println(cavaleiro.movimentar());
        System.out.println(cavaleiro.atacar());
        System.out.println();
        System.out.println(aldeao.movimentar());
        System.out.println(aldeao.atacar());


    }
}
