/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaapicolle;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.Scanner;
import java.util.Stack;

public class App {


    public static void main(String[] args) {

//        ArrayList<String> nomes = new ArrayList<>();
//
//        String s = "juca";
//
//        nomes.add(s);
//        nomes.add("Caio");
//        nomes.add("Ana");
//
//        System.out.println(nomes);

//        for (String elemento : nomes) {
//            System.out.println("Nome: " + elemento);
//        }
//        nomes.forEach(elemento->{
//            System.out.println("Nome " + elemento);
//        });

//        nomes.forEach(System.out::println);


//        String[] v = (String[]) nomes.toArray();


//        double d = 2.3;
//        int i = (int) d;
//        nomes.remove(s);
//
//        System.out.println(nomes);

//        if(!nomes.isEmpty()){
//            nomes.clear();
//        }
        Scanner keyboard = new Scanner(System.in);
        Stack<Integer> numeros = new Stack<>();
        int num = 0;
        while (num != 999){
            System.out.print("Entre com um numero: ");
            num = keyboard.nextInt();
            if(num != 999){
                numeros.add(num);
            }
        }
        numeros.sort(Comparator.naturalOrder());
        System.out.println(numeros);



    }
}
